### ISSUE TITLE
Feed link leads to 404

### ISSUE THREAD

**Issue by nortti0** [M680x0/m680x0.github.io#4]
As far as I can tell, every page on the m680x0.github.io page links to a non-existent atom feed at https://m680x0.github.io/feed.xml in the footer. They also have `<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="M68k LLVM Feed">`

**Comment by mshockwave** [comment]
Thanks for reporting! 
This should be [fixed](https://github.com/M680x0/m680x0.github.io/commit/a9742f6676c9edf9383b62949ebc414c3f5ebb65) now. Feel free to reopen if it doesn't work on your side.

**Comment by nortti0** [comment]
The feed works now, aye. Thank you :)
